### ISSUE TITLE
Wired on big file size loading 

### ISSUE THREAD

**Issue by Ethern0T** [Pkcs11Admin/Be.HexEditor#3]
When loading a big file (4TB image file) the controls acts like crazy,
no offset ; ( instead of 003FC4D0 we get ?????????????)
scroolbar doesn't work as expected.

**Comment by jariq** [comment]
Please report any issues to the [official hexbox project hosted on sourceforge.net](http://sourceforge.net/projects/hexbox/). This repository serves only as a mirror.
